services:
  drone:
    build: ./drone
    environment:
      RUNNING_IN_DOCKER: 1
    deploy:
      replicas: 5
    env_file:
      - path: ./drone/.env
    volumes:
      - ./drone:/drone
     # - ./drone/drone_id:/home/pi/drone_id

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    env_file:
      - path: ./backend/.env
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/health"]
      interval: 5s
      timeout: 3s
      retries: 5
    depends_on:
      - broker

  frontend:
    build: ./frontend
    ports:
      - "5173:80"
    env_file:
      - path: ./frontend/.env
    depends_on:
      backend:
        condition: service_healthy

  broker:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"